# In this file users, backendroles and hosts can be mapped to search guard roles.
# What a role is allowed to do you specify in sg_roles.yml
sg_role_admin:
   backendroles:
    - admin

sg_role_service-acct:
  backendroles:
    - service-acct

